---
- name: Provisioning monitoring 
  hosts: [grafana]
  remote_user: ansible
  become: true

  roles: 
      - grafana    
      - docker
      - apache
 
  environment:
     http_proxy: "http://192.168.x.x:8080" 
     https_proxy: "http://192.168.x.x:8080"
     no_proxy: "127.0.0.1, localhost" 
