- name:  docker restart
  service: name=docker state=restarted

- name:  systemctl daemon-reload
  service: name=systemctl state=daemon-reload

- name: restart prometheus
  command: docker restart prometheus
